insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Napkin - Cocktail,beige 2 - Ply', 88.93);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Sogrape Mateus Rose', 243.85);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Cookies - Englishbay Wht', 498.68);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Pork - Bacon, Double Smoked', 684.85);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Pork - Sausage, Medium', 498.39);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Cherries - Maraschino,jar', 621.38);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'V8 - Berry Blend', 894.46);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Tomatoes - Yellow Hot House', 647.31);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Scallop - St. Jaques', 592.57);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Celery Root', 969.22);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Asparagus - Green, Fresh', 98.98);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Shrimp - Baby, Cold Water', 957.83);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Bread - Pain Au Liat X12', 767.97);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Rice - 7 Grain Blend', 676.63);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Pate - Peppercorn', 899.1);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Alsace Riesling Reserve', 979.8);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Butter Sweet', 270.1);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Crab - Claws, 26 - 30', 873.41);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Pinot Noir Mondavi Coastal', 619.55);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Ice - Clear, 300 Lb For Carving', 317.32);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Pasta - Gnocchi, Potato', 874.2);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Spring Roll Veg Mini', 981.34);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Galliano', 740.9);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Sprouts - Onion', 341.8);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Vinegar - Rice', 115.17);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Bread Roll Foccacia', 386.98);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Coconut - Whole', 619.13);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Energy Drink', 418.79);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Muffin Mix - Chocolate Chip', 267.65);
insert into product (id, product_name, price) values (NEXTVAL('hibernate_sequence'), 'Juice - Mango', 885.01);
